### ISSUE TITLE
issues retrieving data from powerbi sample

### ISSUE THREAD

**Issue by warrendev01** [CiscoDevNet/webex-contact-center-api-samples#158]
have compiled the powerbi sample and running locally on my pc. 
Webpage loads correctly, logs into webex for first time load and get graphql-sample-java homepage with graphql endpoints. When i load any graphql link i get the following error. 
**{"Exception" : "401 Unauthorized: [no body]"}**

any idea on where to continue troubleshooting for this error?

23-06-2023 12:26:52.002 [http-nio-8080-exec-3] ERROR c.w.a.d.controller.WebRestController.endpointName - Exception
org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
        at com.webexcc.api.demo.service.SearchGraphQLService.doSearch(SearchGraphQLService.java:52)
        at com.webexcc.api.demo.controller.WebRestController.endpointName(WebRestController.java:184)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

**Comment by jiwyatt** [comment]
Go to https://developer.webex-cx.com/my-apps and create your app credentials.

 Edit graphql-powerbi-sample/src/main/resources/application.properties

#this values comes from https://admin.webex.com/
organizationId=
#this values comes from my-apps
client_id=
#this values comes from my-apps
client_secret=


restart the app and use the user you used to login into https://developer.webex-cx.com/my-apps.

Jim


From: warrendev01 ***@***.***>
Date: Thursday, June 22, 2023 at 9:28 PM
To: CiscoDevNet/webex-contact-center-api-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CiscoDevNet/webex-contact-center-api-samples] issues retrieving data from powerbi sample (Issue #158)

have compiled the powerbi sample and running locally on my pc.
Webpage loads correctly, logs into webex for first time load and get graphql-sample-java homepage with graphql endpoints. When i load any graphql link i get the following error.
{"Exception" : "401 Unauthorized: [no body]"}

any idea on where to continue troubleshooting for this error?

23-06-2023 12:26:52.002 [http-nio-8080-exec-3] ERROR c.w.a.d.controller.WebRestController.endpointName - Exception
org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
at com.webexcc.api.demo.service.SearchGraphQLService.doSearch(SearchGraphQLService.java:52)
at com.webexcc.api.demo.controller.WebRestController.endpointName(WebRestController.java:184)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

**Comment by warrendev01** [comment]
Thanks Jim, I tried resetting the credentials again just in case i had it wrong. Still received the same result. 
i am running the powerbi-sample currently
The Springboot application  runs fine and asks for first time authentication. this goes through fine and i can see the console showing and refreshing the current token. This token works on the cisco test site as well so i know it is correct. 

However when i load the webpage and select an endpoint this is where i get 401 unauthorized [No Body] error in the console. 
Any other ideas to test would be great.

**Comment by jiwyatt** [comment]
I will download the project and try it from my localhost and provide next steps.


Jim


From: warrendev01 ***@***.***>
Date: Monday, June 26, 2023 at 6:49 PM
To: CiscoDevNet/webex-contact-center-api-samples ***@***.***>
Cc: Jim Wyatt (jiwyatt) ***@***.***>, Comment ***@***.***>
Subject: Re: [CiscoDevNet/webex-contact-center-api-samples] issues retrieving data from powerbi sample (Issue #158)

Thanks Jim, I tried resetting the credentials again just in case i had it wrong. Still received the same result.
i am running the powerbi-sample currently
The Springboot application runs fine and asks for first time authentication. this goes through fine and i can see the console showing and refreshing the current token. This token works on the cisco test site as well so i know it is correct.

However when i load the webpage and select an endpoint this is where i get 401 unauthorized [No Body] error in the console.
Any other ideas to test would be great.

**Comment by jiwyatt** [comment]
I tested from my localhost and did not have any issues.

Do you have some time this week meet and share screens?

I am in central time zone.

Jim


From: Jim Wyatt (jiwyatt) ***@***.***>
Date: Tuesday, June 27, 2023 at 5:30 PM
To: CiscoDevNet/webex-contact-center-api-samples ***@***.***>
Cc: Comment ***@***.***>
Subject: Re: [CiscoDevNet/webex-contact-center-api-samples] issues retrieving data from powerbi sample (Issue #158)
I will download the project and try it from my localhost and provide next steps.


Jim


From: warrendev01 ***@***.***>
Date: Monday, June 26, 2023 at 6:49 PM
To: CiscoDevNet/webex-contact-center-api-samples ***@***.***>
Cc: Jim Wyatt (jiwyatt) ***@***.***>, Comment ***@***.***>
Subject: Re: [CiscoDevNet/webex-contact-center-api-samples] issues retrieving data from powerbi sample (Issue #158)

Thanks Jim, I tried resetting the credentials again just in case i had it wrong. Still received the same result.
i am running the powerbi-sample currently
The Springboot application runs fine and asks for first time authentication. this goes through fine and i can see the console showing and refreshing the current token. This token works on the cisco test site as well so i know it is correct.

However when i load the webpage and select an endpoint this is where i get 401 unauthorized [No Body] error in the console.
Any other ideas to test would be great.

**Comment by arubhatt** [comment]
Hello @warrendev01 - we are marking this issue inactive. Please feel free to reach out with the specifics requested earlier so we can understand the root cause and provide remediation. Thanks!
